export const mockSettingsData={
    main:{
        isFetching:false,
        err:0,
        msg:{
            text:'ok',
            status:'success'
        }
    },
    settings:{
        general:{
            addSource:false
        },
        post:{
            addThumbnail:true,
            parseOtherPictures:false,
            showPicturesDialog:true,
            maxPictures:5,
        },
        gallery:{
            addGallery:false,
            shortCode:undefined,
            parameterName:undefined
        }
}
}